version: 1
objects:
  queue:
    class: multiprocessing.Queue
    maxsize: 10000
formatters:
  simple:
    format: '[%(asctime)s - %(levelname)s] %(name)s - %(processName)s: %(msg)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    filename: 'api.log'
    formatter: simple
  queue_listener:
    class: app.log_utils.logger_util.QueueListenerHandler
    handlers:
      #- cfg://handlers.console
      - cfg://handlers.file
    queue: cfg://objects.queue
loggers:
  __main__:
    level: WARNING
    handlers:
      - queue_listener
    propagate: false
  run:
    level: WARNING
    handlers:
      - queue_listener
    propagate: false
  app.api:
    level: WARNING
    handlers:
      - queue_listener
    propagate: false
  app.reduction.ValidationResultTransmitter:
    level: WARNING
    handlers:
      - queue_listener
    propagate: false
  app.multiprocessing.contactSource:
    level: WARNING
    handlers:
      - queue_listener
    propagate: false
  app.multiprocessing.runner:
    level: WARNING
    handlers:
      - queue_listener
    propagate: false
  app.multiprocessing.functions:
    level: WARNING
    handlers:
      - queue_listener
    propagate: false
  app.multiprocessing.Xgoptional.Xgoptional:
    level: WARNING
    handlers:
      - queue_listener
    propagate: false
  app.multiprocessing.Xjoin.Xjoin:
    level: WARNING
    handlers:
      - queue_listener
    propagate: false
  app.reduction.s2spy.ReducedShapeSchema:
    level: WARNING
    handlers:
      - queue_listener
    propagate: false
  app.reduction.s2spy.ReducedShapeParser:
    level: WARNING
    handlers:
      - queue_listener
    propagate: false
  app.reduction.travshacl.ReducedShapeSchema:
    level: WARNING
    handlers:
      - queue_listener
    propagate: false
  app.reduction.travshacl.ReducedShapeParser:
    level: WARNING
    handlers:
      - queue_listener
    propagate: false
  app.output.simpleOutput:
    level: WARNING
    handlers:
      - queue_listener
    propagate: false
  app.output.statsCalculation:
    level: WARNING
    handlers:
      - queue_listener
  app.query:
    level: WARNING
    handlers:
      - queue_listener
    propagate: false
  rdflib.term:
    level: WARNING
    handlers:
      - queue_listener
    propagate: false
  rdflib:
    level: ERROR
    handlers:
      - queue_listener
    propagate: false
  rdflib.term:
    level: ERROR
    handlers:
      - queue_listener
    propagate: false
root:
  level: WARNING
  handlers:
    - console
